# Generated by Django 2.1.1 on 2018-10-28 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('available_quantity', models.IntegerField(max_length=9)),
                ('price', models.IntegerField(max_length=11)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('is_deleted', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'nam'), ('f', 'nữ')], max_length=2),
        ),
        migrations.AddField(
            model_name='lot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Product'),
        ),
    ]
