# Generated by Django 2.0.2 on 2018-10-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0003_auto_20181031_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateTimeField(default=''),
        ),
    ]
