# Generated by Django 2.1.1 on 2018-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0004_auto_20181031_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avt',
            field=models.ImageField(null=True, upload_to='images/user'),
        ),
    ]
