# Generated by Django 2.1.1 on 2018-10-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0005_user_avt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
