# Generated by Django 2.1.1 on 2018-11-22 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0008_auto_20181031_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default='')),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('succ', 'Thành công'), ('fail', 'Thất bại'), ('proc', 'Đang xử lí')], default='proc', max_length=4)),
                ('payment', models.CharField(choices=[('pp', 'paypal'), ('tm', 'tiền mặt')], max_length=4)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_phone', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateField(default='')),
                ('finish_time', models.DateField(default='')),
                ('sale_off', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Event'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Product'),
        ),
    ]
