# Generated by Django 2.1.1 on 2018-11-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0009_auto_20181122_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Event'),
        ),
    ]
