# Generated by Django 2.1.1 on 2018-11-22 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0010_auto_20181122_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
