# Generated by Django 2.1.3 on 2018-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0011_auto_20181122_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
