# Generated by Django 2.1.3 on 2018-12-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0012_auto_20181207_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=400)),
                ('created_date', models.TimeField()),
                ('image', models.ImageField(upload_to='images/comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
