# Generated by Django 2.1.3 on 2018-12-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0014_auto_20181207_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(default='xxxxx', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='sale_off',
            field=models.IntegerField(),
        ),
    ]
