# Generated by Django 2.1.3 on 2018-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0016_auto_20181211_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
