# Generated by Django 2.1.3 on 2018-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_store', '0017_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('fin', 'Kết thúc'), ('pen', 'Sắp diễn ra'), ('act', 'Đang diễn ra')], default='act', max_length=4),
        ),
    ]
